Consent reminder setup
skunkwork-dev/consent-reminder pull request #1
Opened 2021-12-13 04:51 UTC by VinayJariya

Resolves JIRA Ticket: [PE-2419](https://thriveworks.atlassian.net/browse/PE-2419),  [PE-2420](https://thriveworks.atlassian.net/browse/PE-2420)

UXPin - Figma Link

Briefing
Cron Job for sending consent reminder to patients and summary to support.

Associated PRs
Subtask of  [PE-2244](https://thriveworks.atlassian.net/browse/PE-2244)

How to test:
Instructions for testing locally, including data setup steps, etc..

2021-12-13 12:51 UTC, akash-rajput commented on config.js
> +const isOffline = process.env.IS_OFFLINE === 'true';
this file is duplicated across multiple repos. We can move this to a common package. Please add a TODO for now.

2021-12-13 12:59 UTC, prakash-velotio requested changes

2021-12-13 12:59 UTC, prakash-velotio commented on config.js
> +  'POSTGRES_HOST', 'POSTGRES_PORT', 'POSTGRES_DATABASE', 'POSTGRES_USER','POSTGRES_PASSWORD', 'POSTGRES_POOL_SIZE',
Use read replica here

2021-12-13 12:59 UTC, prakash-velotio commented on config.js
> +const isOffline = process.env.IS_OFFLINE === 'true';
Yupp,
We also have multiple interfaces getting duplicated across repos, Lets create central repo in next sprint

2021-12-13 12:59 UTC, prakash-velotio commented on index.js
> +    const { ENV, HAS_READ_REPLICA } = event;
We enabled read replica for stage and prod and for dev and qa we can use same db values in read replica variable on ssm

2021-12-13 12:59 UTC, prakash-velotio commented on index.js
> +             const bookAppointmentConsent = patientConsent.find(consent => {
can we move this part to query ? 
Fetch only those patients along with appt. who has not provided consent

2021-12-13 12:59 UTC, prakash-velotio commented on index.js
> +};
linter fix

2021-12-13 12:59 UTC, prakash-velotio commented on mailgun.js
> +};
Same linter

2021-12-13 13:02 UTC, akash-rajput requested changes

2021-12-13 13:02 UTC, akash-rajput commented on index.js
> +             const bookAppointmentConsent = patientConsent.find(consent => {
```suggestion
             const isConsentProvided = patientConsent.find(consent => {
```

2021-12-14 04:59 UTC, VinayJariya commented on index.js
> +             const bookAppointmentConsent = patientConsent.find(consent => {
Query will get complex. Lets keep it here only

2021-12-14 06:30 UTC, prakash-velotio commented on .gitignore
> +.env
linter fix

2021-12-14 06:30 UTC, prakash-velotio commented on .env.example
> +POSTGRES_HOST=<placeholder>
Update these vars to match read replica naming convention

2021-12-14 07:46 UTC, prakash-velotio commented on .env.example
> +POSTGRES_HOST_READ=<placeholder>
@VinayJariya Are you sure these are correct names ?
I think they are different from what @akashjobanputra has added

2021-12-14 07:48 UTC, prakash-velotio commented on config.js
> +      .getParameters({ Names: paramNames, WithDecryption: true })
@VinayJariya Are you sure all the vars are getting pulled here ?
@akashjobanputra What is the fetch limit of vars ?

2021-12-14 08:11 UTC, akash-rajput commented on config.js
> +      .getParameters({ Names: paramNames, WithDecryption: true })
10

2021-12-14 08:47 UTC, prakash-velotio approved these changes

2021-12-14 08:47 UTC, merged